version: '3'

services:
  db:
    container_name:  db
    image: mysql:8
    ports:
      - '5000:3307'
    # volumes:
    #   - "/mnt/mysql:/var/lib/mysql"
    environment:
       MYSQL_DATABASE: 'django_blog_posts'
      #  MYSQL_USER: 'root'
      #  MYSQL_PASSWORD: 'ahmad'
       MYSQL_ROOT_PASSWORD: 'root'
      #  MYSQL_ALLOW_EMPTY_PASSWORD: yes
  web:
    container_name:  blog-post
    build: .
    command: #python manage.py makemigrations && python manage.py migrate && \
              python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db