# Generated by Django 4.2.4 on 2023-08-23 03:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='passwordhistory',
            options={'verbose_name': 'User Password History', 'verbose_name_plural': 'User Password Histories'},
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Requested Date'),
        ),
        migrations.AlterField(
            model_name='passwordhistory',
            name='user_id',
            field=models.IntegerField(verbose_name='User Key'),
        ),
    ]
