# Generated by Django 4.2.4 on 2023-09-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auths', '0003_auto_20230923_1713'),
    ]

    operations = [
    ]
