# Generated by Django 4.2.4 on 2023-08-23 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreatePostModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('api', 'API'), ('web', 'web')], max_length=100, verbose_name='Post Source')),
                ('title', models.CharField(max_length=500, verbose_name='Post Title')),
                ('tags', models.CharField(max_length=500, verbose_name='Post Tags')),
                ('descrip', models.CharField(max_length=10000)),
                ('should_display', models.BooleanField()),
            ],
            options={
                'verbose_name': 'User Post',
                'verbose_name_plural': 'User Posts',
            },
        ),
    ]
