# Generated by Django 4.2.4 on 2023-08-23 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0002_createpostmodel_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpostmodel',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='createpostmodel',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
