# Generated by Django 4.2.4 on 2023-08-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_v1', '0003_createpostmodel_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='createpostmodel',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterModelTable(
            name='createpostmodel',
            table='create_posts',
        ),
    ]
