# Generated by Django 4.2.4 on 2023-09-23 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('api_v1', '0004_rename_user_id_createpostmodel_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpostmodel',
            name='site',
            field=models.ManyToManyField(to='sites.site'),
        ),
    ]
